modLoader = "kotlinforforge" #mandatory
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

issueTrackerURL="https://github.com/Evoloxi/Taurine/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Evoloxi" #optional
#logoFile="taurine.png" #optional
#credits="" #optional
authors = "${mod_authors}" #optional

description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "vanillin"
type = "required"
versionRange = "[${vanillin_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "flywheel"
type = "required"
versionRange = "[${flywheel_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "[${create_version},)"
ordering = "NONE"
side = "CLIENT"

#[features."${mod_id}"]
#openGLVersion="[3.2,)"
